// This file is automatically generated. Do not edit it directly.
// (except these fallback values below, which are safe to add)

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Try to read from env vars (local dev / Vercel), otherwise use explicit fallback
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://wsepwuxkwjnsgmkddkjw.supabase.co"; // 🔁 Replace with your actual Supabase URL

const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzZXB3dXhrd2puc2dta2Rka2p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3ODg5ODUsImV4cCI6MjA3NTM2NDk4NX0.B4KktUFp_WLh55A5ZEP64NApI_ZttDZLA1IqP5FK9BI"; // 🔁 Replace with your real anon (public) key

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
